/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-10-20 07:05:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class FizzBuzz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>FizzBuzz - YLabCoder</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/YLabCoder/bootstrap/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/YLabCoder/bootstrap/css/bootstrap.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h2 class=\"page-header\">FizzBuzz</h2><br />\n");
      out.write("\n");
      out.write("\n");
      out.write("<form method=\"POST\" action=\"submit\">\n");
      out.write("<h4>Question:\n");
      out.write("\n");
      out.write("\n");
 String root = "/Users/admin/junit/"; 
      out.write('\n');
 File file = new File(root); 
      out.write("\n");
      out.write("\n");
      out.write("<select name=\"name\">\n");

for(File qfile : file.listFiles()){ 
	if(!qfile.isDirectory()) continue;
	String name = qfile.getName();
	out.print("<option value=\"" + name + "\">" + name + "</option>");
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</h4>\n");
      out.write("\n");
      out.write("<h4>Input Code:</h4>\n");
      out.write("<p><textarea name=\"submited_code\" rows=\"20\" cols=\"100\"></textarea></p>\n");
      out.write("\n");
      out.write("<p><input type=\"submit\" value=\"Submit\" class=\"btn btn-primary\"></p>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
